DASOM-GitHub/dasom-web-frontend

src/App.tsx, src/assets/images/headerMenu.svg, src/components/UI/Header.tsx, src/components/layout/mobileLayout.tsx
- #1 
- 헤더 추가
- 헤더 구현
- HeaderMenu.svg 추가
- 기존 mobileLayout(lowerCamelCase)에서 UpperCamelCase로 변경
=> [feat] 헤더구현

postcss.config.js, src/App.tsx, src/assets/styles/index.css, src/components/UI/Header.tsx, src/pages/Main.tsx, tailwind.config.js
- #3 
- tailwind 기존 설정에 오류가 있어 수정했습니다.
- 곰곰히 생각해보니 헤더에 Props를 잘 안쓸거 같아 삭제했습니다.
- 메인화면 만들어서 헤더 한번 출력해봤습니다.
- 헤더 진짜 완료. 추후 클릭 이벤트 생성 예정
=> [fix] 헤더 테스트 및 tailwind 설정 수정

src/components/UI/Header.tsx
- 예시: #27 
- 헤더 팝업 아래로 컴포넌트가 생기는 문제 해결
- fixed inset-0 추가해서 화면 전체 덮음
- z-40 추가해서 헤더보다 아래, 다른 컴포넌트보다 위에 배치
- MobileLayout 밖에서 화면 렌더링 시켰습니다.
=> [fix] 헤더 팝업 에러수정

src/components/layout/MobileLayout.tsx
- #29 
- height 설정 조정
- height: '100vh',
overflowY: 'auto',
그냥 이거 두줄 추가해줬습니다
=> [fix] MobileLayout 오류 수정

src/App.tsx, src/pages/Login.tsx, src/pages/UserMain.tsx
- #36 
- 로그인 기능 수정 완료했습니다
- 헤더로 토큰 받아서 로컬에 저장
- 관리자 계정은 /admin으로 일반멤버는 /usermain 으로 리다이렉트
=> [fix] 로그인 구현 완료

.github/workflows/dev.yml
- #47 
- github actions 설정용 파일 추가
- 환경설정 파일 중 하나인 dev.yml 추가했습니다
=> [infra] Create dev.yml

src/App.tsx
- #45 
- App.tsx 코드를 다시 수정했습니다
- 어제 회의 때 로그인 pr 에서 App.tsx 수정할 때 잘못 이해하고 고쳐놔서 다시 수정했습니다. 죄송합니다.
=> [fix] App.tsx 수정

src/components/UI/Recruit_InputField.tsx, src/pages/Recruit.tsx
- #52 
-  grade 초기 값 1로 변경
- onKeydown 메소드 추가 
-  제약조건 추가
=> [feat] Recruit 페이지 api 기능 추가

vercel.json
- #53
- vercel.json 파일추가
- 배포환경이 맞게끔 수정했습니다
=> [hotfix] vercel용 환경설정 파일 추가

src/components/UI/Header.tsx, src/components/UI/PythonEditor.tsx, src/pages/Main.tsx
- #72 
- 기존 파이썬 코드블럭을 컴포넌트화 했습니다
- 파이썬 코드블럭, 타이핑 이펙트부분을 PythonEditor.tsx에서 처리하게끔 변경
=> [refactor] 메인페이지 코드 간결화

src/components/UI/ParticlesBackground.tsx, src/pages/Main.tsx
- #76 
- 메인페이지 백그라운드 수정
- particles 배경 컴포넌트를 추가해 메인 백그라운드에 적용시켰습니다.
=> [design] 메인페이지 디자인 수정

src/App.tsx, src/components/layout/ProtectRoute.tsx
- #83 
- 토큰 여부 확인하는 컴포넌트 추가해서 필요한 Route 부분에 추가했습니다.
- ProtecteRoute로 감싸진 컴포넌트는 토큰이 있어야 접근 가능하도록 구현했습니다. 없으면 메인페이지로 돌아가게 했습니다.
=> [fix] 어드민 페이지 접근 보안 추가

package.json, yarn.lock
- #85 
- 기존에 있던 package.json, yarn.lock 파일에 swiper 라이브러리 추가
- newsInfo 페이지 슬라이드 기능으로 인한 라이브러리 설치
=> [feat] swiper 라이브러리 설치

src/App.tsx, src/assets/styles/index.css, src/components/layout/MobileLayout.tsx, src/index.tsx, tailwind.config.js
- #93 
- 모바일 레이아웃에서 스크롤바가 안보이게 수정
- tailwind에는 자체지원하는 기능이 없어 커스텀 클래스 만들어서 MobileLayout부분에 추가했습니다.
- 기타 App.tsx 등 일단 보인 부분만 인덴테이션 좀 맞춰놨습니다.
=> [design] 스크롤바 hidden 설정

src/components/UI/RecruitUI.tsx, src/components/UI/Recruit_InputField.tsx, src/pages/Recruit.tsx
- #100 
- RecruitUI 컴포넌트 도메인 주소 변경
- Recruit_Inputfield 컴포넌트 type 추가
- 도메인 api.or.kr 수정
- minLength, maxLength, 타입 추가하여 최소 1글자에서 최대 16글자로 제약조건 추가
=> feat: 도메인주소 변경 & 이름 필드 제약조건 추가

src/components/UI/RecruitUI.tsx
- #105 
- Recruit_SUB, SUB2, FINAL, FINAL2 컴포넌트 넓이 수정
- w-auto로 수정 & pr-2 제거
=> [fix] 합격여부 컴포넌트 레이아웃 수정

public/index.html
#[fix] 지원자 폼 페이지 자동확대 방지
- #115 
- index.html에 코드 추가
- meta 태그 안에 user-scalable=no 속성 추가
=> [fix] 지원자 폼 페이지 자동확대 방지

public/index.html, src/assets/styles/index.css
=> [fix] 지원자 폼 자동확대 방지 

src/pages/RecruitMeeting.tsx
- #119 
- RecruitMeeting 컴포넌트에서 Recruit_InfoBanner 위치 변경
=> [fix] 면접예약 페이지 배너 수정

src/pages/Login.tsx, src/pages/News.tsx, src/pages/NewsInfo.tsx, src/pages/RecruitResult.tsx
- #124 
- 뉴스 최신순 정렬, console.log 주석
- 뉴스페이지 최신순 정렬
- 어드민 페이지 제외하고 console.log로 데이터 찍히는 거 몇 개 주석처리 했습니다
=> [fix] 뉴스 페이지 최신순 정렬

src/pages/Login.tsx, src/pages/News.tsx, src/pages/NewsInfo.tsx, src/pages/RecruitResult.tsx
* fix: News.tsx sort함수 수정
* fix: 서비스 페이지 중 console.log 주석 처리
=> fix: 뉴스 페이지 최신순 정렬

src/pages/RecruitResult.tsx
=> feat: RecriotCheck 페이지 제약조건 추가

src/components/UI/RecruitUI.tsx, src/pages/RecruitSubmitMeeting.tsx
- #132 
- 면접 장소 (다솜 동방 호실) 텍스트 추가
- 면접 장소 (다솜 동방 호실) 텍스트 추가
=> [fix] 면접 장소 안내 없음 수정

src/pages/Recruit.tsx
=> version control v1.0.4

src/pages/Recruit.tsx
- #138 
- 체크박스 교차검증 추가
- 체크박스 교차검증 추가
=> [fix] 체크박스 교차검증

src/pages/Recruit.tsx
=> v1.0.5 체크박스 필수처리 추가

src/pages/Login.tsx, src/pages/RecruitMeeting.tsx, src/pages/RecruitResult.tsx, src/pages/admin/ManApplicants.tsx, src/pages/admin/ManNewsDetail.tsx, src/pages/admin/ManNewsList.tsx, src/pages/admin/ManNewsPost.tsx, src/pages/admin/ManRecruitDate.tsx
- #147 
- 로그 주석처리
- 각자 작업하신 페이지 로그 주석처리된 부분 확인하고 문제 없으시면 approve 이건 로그 남기는게 나을거 같다 하시면 코멘트 남겨주시면 됩니다. error 로 작업해두신 부분은 일부러 주석처리 하지 않았습니당
=> [refactor] 디버깅용 로그 주석처리

src/pages/Login.tsx, src/pages/RecruitMeeting.tsx, src/pages/RecruitResult.tsx, src/pages/admin/ManApplicants.tsx, src/pages/admin/ManNewsDetail.tsx, src/pages/admin/ManNewsList.tsx, src/pages/admin/ManNewsPost.tsx, src/pages/admin/ManRecruitDate.tsx
=> v1.0.7 로그 주석처리

src/components/UI/MailButtons.tsx
=> [refactor] 코드 오타 수정

src/components/UI/Header.tsx
- #152 
- 기간에 따라 모집 폼 접근 텍스트 비활성화
- useEffect로 상태관리
=> [feat] 헤더 로직 수정

.github/workflows/jira-integration.yml
=> hotfix/dasomfe 10 자동연결 버그

src/App.tsx, src/components/UI/RecruitUI.tsx, src/components/UI/Recruit_Button.tsx, src/components/UI/Recruit_InfoBanner.tsx, src/components/UI/Recruit_InputField.tsx, src/components/layout/MobileLayout.tsx, src/pages/recruit/Recruit.tsx, src/pages/recruit/RecruitCheck.tsx, src/pages/recruit/RecruitCheckFinal.tsx, src/pages/recruit/RecruitInfo.tsx, src/pages/recruit/RecruitMeeting.tsx, src/pages/recruit/RecruitResult.tsx, src/pages/recruit/RecruitSubmit.tsx, src/pages/recruit/RecruitSubmitMeeting.tsx, src/pages/recruit/Recruittype.ts, src/pages/recruit/SomkathonRecruit.tsx, src/pages/recruit/SomkathonSubmit.tsx, src/pages/recruit/useRecruitForm.ts, src/pages/recruit/useRecruitSchedule.ts
- #205 
- 데스크탑 뷰 레이아웃 수정 (모바일 뷰는 기존 그대로 사용)
- recruit 관련 페이지 및 컴포넌트 데스크탑 뷰 폰트 크기 수정
- recruit 관련 페이지 footer 숨김 처리
- PR을 제출하기 전에 다음 사항들을 확인해주세요:
=> [refactor] 지원 관련 페이지 레이아웃 수정

src/components/sections/ActivitiesSection.tsx
- #216 
- Link 컴포넌트 props 도메인 값 변경
- PR을 제출하기 전에 다음 사항들을 확인해주세요:
- 특별히 리뷰해주길 원하는 부분
=> [bug] ActivitiesSection 페이지 뉴스 도메인 변경

src/pages/CoreMembers.tsx
- 조직도 api를 연동했습니다
- PR을 제출하기 전에 다음 사항들을 확인해주세요:
=> [hotfix] 조직도 api 연동
